export type WebApiStatusTag = 'deprecated' | 'experimental' | 'non_standard'

export type WebApiEntry = {
    readonly name: string
    readonly tags?: readonly WebApiStatusTag[]
}

export const WEB_API_FULL_LIST_SOURCE = 'https://developer.mozilla.org/en-US/docs/Web/API'
export const WEB_API_FULL_LIST_CAPTURED_AT = '2026-04-08'

const WEB_API_CATALOG: readonly WebApiEntry[] = [
    { name: 'Attribution Reporting API', tags: ['deprecated'] },
    { name: 'Audio Output Devices API', tags: ['experimental'] },
    { name: 'Audio Session API', tags: ['experimental'] },
    { name: 'Background Fetch API', tags: ['experimental'] },
    { name: 'Background Synchronization API' },
    { name: 'Background Tasks API' },
    { name: 'Badging API' },
    { name: 'Barcode Detection API', tags: ['experimental'] },
    { name: 'Battery Status API' },
    { name: 'Beacon API' },
    { name: 'Broadcast Channel API' },
    { name: 'CSS Custom Highlight API' },
    { name: 'CSS Font Loading API' },
    { name: 'CSS Painting API', tags: ['experimental'] },
    { name: 'CSS Properties and Values API' },
    { name: 'CSS Typed Object Model API' },
    { name: 'CSS Object Model (CSSOM)' },
    { name: 'CSSOM view API' },
    { name: 'Canvas API' },
    { name: 'Channel Messaging API' },
    { name: 'Clipboard API' },
    { name: 'Compression Streams API' },
    { name: 'Compute Pressure API', tags: ['experimental'] },
    { name: 'Console API' },
    { name: 'Contact Picker API', tags: ['experimental'] },
    { name: 'Content Index API', tags: ['experimental'] },
    { name: 'Cookie Store API' },
    { name: 'Credential Management API' },
    { name: 'Document Object Model (DOM)' },
    { name: 'Device Memory API' },
    { name: 'Device orientation events' },
    { name: 'Device Posture API', tags: ['experimental'] },
    { name: 'Document Picture-in-Picture API', tags: ['experimental'] },
    { name: 'EditContext API', tags: ['experimental'] },
    { name: 'Encoding API' },
    { name: 'Encrypted Media Extensions API' },
    { name: 'EyeDropper API', tags: ['experimental'] },
    {
        name: 'Federated Credential Management (FedCM) API',
        tags: ['experimental'],
    },
    { name: 'Fenced Frame API', tags: ['experimental'] },
    { name: 'Fetch API' },
    { name: 'File API' },
    { name: 'File System API' },
    { name: 'File and Directory Entries API' },
    { name: 'Force Touch events', tags: ['non_standard'] },
    { name: 'Fullscreen API' },
    { name: 'Gamepad API' },
    { name: 'Geolocation API' },
    { name: 'Geometry interfaces' },
    { name: 'HTML DOM API' },
    { name: 'HTML Drag and Drop API' },
    { name: 'HTML Sanitizer API' },
    { name: 'History API' },
    { name: 'Houdini APIs' },
    { name: 'Idle Detection API', tags: ['experimental'] },
    { name: 'IndexedDB API' },
    { name: 'Ink API', tags: ['experimental'] },
    { name: 'InputDeviceCapabilities API', tags: ['experimental'] },
    {
        name: 'Insertable Streams for MediaStreamTrack API',
        tags: ['experimental'],
    },
    { name: 'Intersection Observer API' },
    { name: 'Invoker Commands API' },
    { name: 'JS Self-Profiling API', tags: ['experimental'] },
    { name: 'Keyboard API', tags: ['experimental'] },
    { name: 'Launch Handler API', tags: ['experimental'] },
    { name: 'Local Font Access API', tags: ['experimental'] },
    { name: 'MediaStream Image Capture API' },
    { name: 'Media Capabilities API' },
    { name: 'Media Capture and Streams API (Media Stream)' },
    { name: 'Media Session API' },
    { name: 'Media Source API' },
    { name: 'MediaStream Recording API' },
    { name: 'Navigation API' },
    { name: 'Network Information API' },
    { name: 'Notifications API' },
    { name: 'Page Visibility API' },
    { name: 'Payment Request API' },
    { name: 'Performance APIs' },
    { name: 'Permissions API' },
    { name: 'Picture-in-Picture API' },
    { name: 'Pointer events' },
    { name: 'Pointer Lock API' },
    { name: 'Popover API' },
    { name: 'Presentation API', tags: ['experimental'] },
    { name: 'Prioritized Task Scheduling API' },
    { name: 'Private State Token API', tags: ['experimental'] },
    { name: 'Push API' },
    { name: 'Remote Playback API' },
    { name: 'Reporting API' },
    { name: 'Resize Observer API' },
    { name: 'SVG API' },
    { name: 'Screen Capture API' },
    { name: 'Screen Orientation API' },
    { name: 'Screen Wake Lock API' },
    { name: 'Selection API' },
    { name: 'Sensor APIs' },
    { name: 'Server-sent events' },
    { name: 'Service Worker API' },
    { name: 'Shared Storage API', tags: ['deprecated'] },
    { name: 'Speculation Rules API', tags: ['experimental'] },
    { name: 'Storage API' },
    { name: 'Storage Access API' },
    { name: 'Streams API' },
    { name: 'Summarizer API', tags: ['experimental'] },
    { name: 'Topics API', tags: ['non_standard', 'deprecated'] },
    { name: 'Touch events' },
    {
        name: 'Translator and Language Detector APIs',
        tags: ['experimental'],
    },
    { name: 'Trusted Types API' },
    { name: 'UI Events' },
    { name: 'URL API' },
    { name: 'URL Fragment Text Directives' },
    { name: 'URL Pattern API' },
    { name: 'User Preferences API', tags: ['experimental'] },
    { name: 'User-Agent Client Hints API', tags: ['experimental'] },
    { name: 'Vibration API' },
    { name: 'View Transition API' },
    { name: 'Viewport Segments API', tags: ['experimental'] },
    { name: 'VirtualKeyboard API', tags: ['experimental'] },
    { name: 'Web Bluetooth API', tags: ['experimental'] },
    {
        name: 'Web Periodic Background Synchronization API',
        tags: ['experimental'],
    },
    { name: 'Web Animations API' },
    { name: 'Web Audio API' },
    { name: 'Web Authentication API' },
    { name: 'Web Components' },
    { name: 'Web Crypto API' },
    { name: 'Web Locks API' },
    { name: 'Web MIDI API' },
    { name: 'Web NFC API', tags: ['experimental'] },
    { name: 'Web Serial API', tags: ['experimental'] },
    { name: 'Web Share API' },
    { name: 'Web Speech API' },
    { name: 'Web Storage API' },
    { name: 'Web Workers API' },
    { name: 'Web-based Payment Handler API', tags: ['experimental'] },
    { name: 'WebCodecs API' },
    { name: 'WebGL: 2D and 3D graphics for the web' },
    { name: 'WebGPU API' },
    { name: 'WebHID API', tags: ['experimental'] },
    { name: 'WebOTP API', tags: ['experimental'] },
    { name: 'WebRTC API' },
    { name: 'WebSocket API (WebSockets)' },
    { name: 'WebTransport API' },
    { name: 'WebUSB API', tags: ['experimental'] },
    { name: 'WebVR API', tags: ['non_standard', 'deprecated'] },
    { name: 'WebVTT API' },
    { name: 'WebXR Device API', tags: ['experimental'] },
    { name: 'Window Controls Overlay API', tags: ['experimental'] },
    { name: 'Window Management API', tags: ['experimental'] },
    { name: 'XMLHttpRequest API' },
] as const

const WEB_API_PERMISSION_REQUIRED_NAMES = new Set<string>([
    'Audio Output Devices API',
    'Barcode Detection API',
    'Clipboard API',
    'Contact Picker API',
    'Device orientation events',
    'Geolocation API',
    'Idle Detection API',
    'Local Font Access API',
    'Media Capture and Streams API (Media Stream)',
    'MediaStream Image Capture API',
    'MediaStream Recording API',
    'Notifications API',
    'Push API',
    'Screen Capture API',
    'Storage Access API',
    'Web Bluetooth API',
    'WebHID API',
    'Web MIDI API',
    'Web NFC API',
    'Web Serial API',
    'Web Speech API',
    'WebUSB API',
    'WebXR Device API',
    'Window Management API',
])

export const WEB_API_WITH_PERMISSIONS_LIST: readonly WebApiEntry[] = WEB_API_CATALOG.filter(
    (entry) => WEB_API_PERMISSION_REQUIRED_NAMES.has(entry.name)
)

export const WEB_API_WITHOUT_PERMISSIONS_LIST: readonly WebApiEntry[] = WEB_API_CATALOG.filter(
    (entry) => !WEB_API_PERMISSION_REQUIRED_NAMES.has(entry.name)
)

export const WEB_API_WITH_PERMISSIONS_NAMES: readonly string[] = WEB_API_WITH_PERMISSIONS_LIST.map(
    (entry) => entry.name
)

export const WEB_API_WITHOUT_PERMISSIONS_NAMES: readonly string[] =
    WEB_API_WITHOUT_PERMISSIONS_LIST.map((entry) => entry.name)
